-- ============================================================================
-- 97_supabase.sql
--
-- Supabase adapter.  ONLY run this file if you are deploying to Supabase
-- (self-hosted on your GCP VM or Supabase Cloud).  For a plain Postgres
-- deployment, skip this file — `current_actor_id()` from 00_setup.sql
-- already reads from a session variable.
--
-- This file:
--   1. Links actors → auth.users (Supabase's GoTrue auth table).
--   2. Replaces current_actor_id() to resolve via auth.uid() so RLS
--      policies in 99_rls.sql work transparently with Supabase Auth JWTs.
--   3. Creates the four evidence storage buckets.
--   4. Adds RLS policies on storage.objects per bucket.
--
-- Worker access pattern: backend workers (gmail_fetch, audio_transcribe, etc.)
-- connect with the Supabase `service_role` key, which bypasses RLS.  That
-- is correct — workers need unrestricted writes.  All human-facing access
-- goes through anon/authenticated keys and is filtered by the policies in
-- 99_rls.sql.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) Link actors → auth.users.
--
-- Each human actor maps 1:1 to a Supabase auth user.  System/service
-- actors leave auth_user_id NULL.
-- ----------------------------------------------------------------------------

ALTER TABLE actors
  ADD COLUMN auth_user_id uuid UNIQUE
    REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX actors_auth_user_idx
  ON actors(auth_user_id) WHERE auth_user_id IS NOT NULL;

COMMENT ON COLUMN actors.auth_user_id IS
  'Supabase auth.users.id for this actor.  NULL for system/service accounts.';

-- ----------------------------------------------------------------------------
-- 2) Replace current_actor_id() to read from JWT via auth.uid().
--
-- The session-variable fallback is preserved for service contexts that
-- haven''t come through Auth (e.g., a SQL runbook executed by an admin
-- with `SET LOCAL app.current_actor_id = ...`).  auth.uid() takes precedence.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION current_actor_id() RETURNS uuid AS $$
  SELECT COALESCE(
    (SELECT id FROM actors
       WHERE auth_user_id = auth.uid() AND is_active
       LIMIT 1),
    NULLIF(current_setting('app.current_actor_id', true), '')::uuid
  )
$$ LANGUAGE sql STABLE;

-- service_role bypasses RLS entirely; we still want audit_log entries
-- to attribute to a system actor.  The application should call:
--   SELECT set_config('app.current_actor_id', '<system-actor-uuid>', true);
-- at the start of any worker transaction so audit rows are non-NULL.

-- ----------------------------------------------------------------------------
-- 3) Storage buckets.
--
-- Buckets are PRIVATE (public=false) — all access is through signed URLs
-- generated by the application after authorization.  Object paths follow
-- the schema's storage_uri convention.
-- ----------------------------------------------------------------------------

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES
  ('raw-evidence',  'raw-evidence',  false, NULL, NULL),
  ('derived',       'derived',       false, NULL, NULL),
  ('productions',   'productions',   false, NULL, NULL),
  ('warc',          'warc',          false, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

COMMENT ON TABLE storage.buckets IS
  'Bucket map: raw-evidence = documents.storage_uri + acquisitions.raw_storage_uri | '
  'derived = document_versions.storage_uri | productions = production deliverables | '
  'warc = docket_snapshots.warc_storage_uri';

-- ----------------------------------------------------------------------------
-- 4) Storage RLS policies on storage.objects.
--
-- Pattern: SELECT requires owner/counsel/paralegal role and (for
-- raw-evidence + derived) a corresponding granted resource.  Workers use
-- service_role and bypass these.  No INSERT/UPDATE/DELETE policy is added
-- for human users — uploads happen through workers (service_role).
--
-- AUDIT-FIX (CRIT-5): every current_actor_role()/current_actor_id() call in
-- the storage policies below is wrapped in a scalar subquery (SELECT ...) so
-- Postgres evaluates it once per statement instead of once per storage object
-- row scanned. Documented Supabase RLS-performance pattern.
-- ----------------------------------------------------------------------------

-- raw-evidence: owner + counsel only by default; paralegal via grant.
CREATE POLICY storage_raw_evidence_read ON storage.objects FOR SELECT
  USING (
    bucket_id = 'raw-evidence'
    AND (
      (SELECT current_actor_role()) IN ('owner', 'counsel')
      OR (
        (SELECT current_actor_role()) = 'paralegal'
        AND EXISTS (
          SELECT 1 FROM acl_grants g
          WHERE g.actor_id = (SELECT current_actor_id())
            AND g.resource_type = 'storage_object'
            AND g.resource_id::text = storage.objects.id::text
            AND 'read' = ANY(g.permissions)
            AND (g.expires_at IS NULL OR g.expires_at > now())
        )
      )
    )
  );

-- derived: owner/counsel/paralegal — derivative renditions like OCR text
-- and image versions are typically the things paralegals work with.
CREATE POLICY storage_derived_read ON storage.objects FOR SELECT
  USING (
    bucket_id = 'derived'
    AND (SELECT current_actor_role()) IN ('owner', 'counsel', 'paralegal')
  );

-- productions: owner/counsel/paralegal can see what was produced.
-- Opposing counsel never reads from this bucket on the live DB; the
-- external review portal queries its own storage namespace.
CREATE POLICY storage_productions_read ON storage.objects FOR SELECT
  USING (
    bucket_id = 'productions'
    AND (SELECT current_actor_role()) IN ('owner', 'counsel', 'paralegal')
  );

-- warc: owner/counsel only — the immutable web captures of court dockets
-- and similar.  Paralegals can read parsed docket_entries via normal RLS,
-- but the raw WARC bytes stay tighter.
CREATE POLICY storage_warc_read ON storage.objects FOR SELECT
  USING (
    bucket_id = 'warc'
    AND (SELECT current_actor_role()) IN ('owner', 'counsel')
  );

-- Default-deny on writes for non-service-role.  Workers run as service_role
-- and bypass RLS entirely.  We document the intent with a no-op comment.
COMMENT ON POLICY storage_raw_evidence_read ON storage.objects IS
  'Read access to raw evidence bucket; writes are service_role only';

-- ----------------------------------------------------------------------------
-- Convenience: a view that joins storage.objects to documents so the app
-- can resolve "which document does this object belong to" without parsing
-- paths client-side.  Bucket-prefixed paths are expected to look like
-- `<sha256-prefix>/<sha256>.<ext>` matching documents.storage_uri.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE VIEW storage_documents_link AS
  SELECT
    o.id              AS object_id,
    o.bucket_id,
    o.name            AS object_path,
    d.id              AS document_id,
    d.sha256,
    d.declared_filename,
    d.evidentiary_pii_tier
  FROM storage.objects o
  LEFT JOIN documents d ON d.storage_uri LIKE '%' || o.name;

-- ----------------------------------------------------------------------------
-- Notes for application wiring:
--
-- * On the client side, every authenticated request to PostgREST/Supabase
--   carries a JWT from auth; auth.uid() inside RLS resolves to the
--   actor automatically.  No SET LOCAL needed.
--
-- * Workers connect with SUPABASE_SERVICE_ROLE_KEY.  At the start of each
--   transaction, run:
--       SELECT set_config('app.current_actor_id', :system_actor_uuid, true);
--   so audit_log entries attribute to the right system actor.  RLS is
--   bypassed regardless because of the service_role.
--
-- * Signed URLs from `supabase.storage.from('raw-evidence').createSignedUrl(...)`
--   should default to short TTLs (e.g., 5 minutes).  Long-lived links
--   defeat the access control we just built.
-- ----------------------------------------------------------------------------
